# Generated by Django 2.2 on 2021-04-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechOutputApp', '0003_remove_speech_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_item',
            name='url',
            field=models.CharField(default="{% static '/speech_items/default.png' %}", max_length=300),
        ),
    ]
