# Generated by Django 2.2 on 2021-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechOutputApp', '0004_speech_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech_item',
            name='name',
        ),
        migrations.AddField(
            model_name='speech_item',
            name='saying',
            field=models.CharField(default='', max_length=300),
        ),
    ]
