# Generated by Django 2.2 on 2021-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechOutputApp', '0005_auto_20210411_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech_item',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
