# Generated by Django 2.2 on 2021-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechOutputApp', '0008_auto_20210417_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
    ]
